server:
  port: 9000

spring:
  application.name: authentication-sevice
  jackson:
    default-property-inclusion: NON_NULL
  db:
    schemas:
      default-schema: system
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/monitoring_system?currentSchema=${spring.db.schemas.default-schema}
    hikari:
      auto-commit: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${spring.db.schemas.default-schema}
        show_sql: true
        use_sql_comments: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      username: redis
      password: password
  auth:
    login:
      uri: http://localhost:3000/login

cache:
  redis:
    cacheNames:
      - cacheName: test
        ttl:
        typeDuration: m

logging:
  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.nimbusds: TRACE
